name: "Task"
description: "Submit a short definite piece of work."
title: "Task:<Short summary of the problem>"
projects: []
type: "Task"
labels: []
body:
- type: textarea
  attributes:
    label: "Goal"
    placeholder: "Clearly stating the goal of the task is crucial for understanding the requirement."
  id: subject
  validations:
    required: true
- type: textarea
  attributes:
    label: "Notes (Optional)"
    placeholder: "Any other useful information, links, screenshots?"
  id: notes
